### ISSUE TITLE
Cannot calculate float number

### ISSUE THREAD

**Issue by haifahrul** [heritechie/gdk-mws-2018-participants-code#1]
Hallo @heritechie ,

I found some issue. 

Your [project calculator](https://heritechie-mws.firebaseapp.com/tugas/minggu-1.html) cannot calculating float number.

**Comment by heritechie** [comment]
Hai @haifahrul , thanks for your feedback.

It's already fix by now.

I change the url for the page to
[Project calculator](https://heritechie-mws.firebaseapp.com/project1/add2numbers.html)

**Comment by haifahrul** [comment]
Hi @heritechie,
Oke dude.
